base_django_template/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from base_django_template import views

urlpatterns = [
    url(r'^$', views.contact, name='contact'),
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^page/$', TemplateView.as_view(template_name='pages/page.html'), name='page'),
    url(r'^thank_you/$', TemplateView.as_view(template_name='pages/thank_you.html'), name='thank_you'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('base_django_template.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

base_django_template/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

base_django_template/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field
from crispy_forms.bootstrap import (
    PrependedText, PrependedAppendedText, FormActions)

class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(required=True, widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Field('contact_name', placeholder="Full Name"),
            Field('contact_email', placeholder="Email Address"),
            Field('content', placeholder=""),
            Submit('sign_in', 'Submit', css_class="btn btn-info"),
            )
        self.fields['contact_name'].label = "Your name:"
        self.fields['contact_email'].label = "Your email:"
        self.fields['content'].label = "Your message:"

base_django_template/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

base_django_template/views.py
from forms import ContactForm
from django.shortcuts import render

from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.template import Context
from django.template.loader import get_template
from django.contrib.auth import get_user_model
from django.shortcuts import render

def contact(request):
    form_class = ContactForm

    # new logic!
    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get('contact_name', '')
            contact_email = request.POST.get('contact_email', '')
            form_content = request.POST.get('content', '')

            # Email the profile with the
            # contact information
            template = get_template('contact/contact_template.txt')
            context = dict({'contact_name': contact_name, 'contact_email': contact_email, 'form_content': form_content,})

            content = template.render(context)

            email = EmailMessage(
                "New contact form submission",
                content,
                "Your website" +'',
                ['steve@steve-shead.com'],
                headers = {'Reply-To': contact_email }
            )
            email.send()
            return render(request, 'pages/thank_you.html')

    return render(request, 'pages/home.html', {
        'form': form_class,
    })

base_django_template/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

base_django_template/templates/base.html
{% load static i18n %}

{% url 'home' as home_url %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Base Django Template{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endblock %}

  </head>

  <body{% if request.get_full_path != home_url %} class="page-padding"{% endif %}>

    <div class="m-b-1" id="home">
  <!-- main nav -->
  <nav id="navbar-spy" class="navbar fixed-top navbar-expand-md navbar-dark bg-dark scrolling-navbar
{% if request.get_full_path != home_url %}pageNav{% endif %}">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'home' %}">S2 <span>Design</span></a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link no-active" {% if request.get_full_path == home_url %}href="#home"{% else %}href="{% url 'home' %}"{% endif %}>Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" {% if request.get_full_path == home_url %}href="#sec1"{% else %}href="{% url 'home' %}#sec1"{% endif %}>Section 1</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" {% if request.get_full_path == home_url %}href="#sec2"{% else %}href="{% url 'home' %}#sec2"{% endif %}>Section 2</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" {% if request.get_full_path == home_url %}href="#sec3"{% else %}href="{% url 'home' %}#sec3"{% endif %}>Section 3</a>
        </li>
      </ul>

      <!-- right nav -->
      <ul class="navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
          </li>
        {% else %}
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="sign-up-link" class="nav-link btn btn-info" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
          </li>
          <li class="nav-item">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
          </li>
        {% endif %}
      </ul>
      <!-- /end right nav -->
    </div>
  </nav>
<!-- /end main nav -->
</div>

    <!-- show the jumbotron on the home page only -->
    {% block splash %}
    {% endblock splash %}

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

<footer class="page-footer center-on-small-only mdb-color lighten-3">

  <!--Footer Links-->
  <div class="container">
    <div class="row my-4">

      <!--First column-->
      <div class="col-md-4 col-lg-4">
        <h5 class="title mb-4 font-bold">Footer Content</h5>
        <p>Fugit, error amet numquam iure provident voluptate esse quasi, veritatis totam</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit, error amet numquam iure provident
            voluptate esse quasi, veritatis totam voluptas nostrum. </p>
      </div>
      <!--/.First column-->

      <hr class="clearfix w-100 d-md-none">

      <!--Second column-->
      <div class="col-md-2 col-lg-2 ml-auto">
          <h5 class="title mb-4 font-bold">About</h5>
              <p><a {% if request.get_full_path == home_url %}href="#home"{% else %}href="{% url 'home' %}"{% endif %}>REWIND</a></p>
              <p><a {% if request.get_full_path == home_url %}href="#sec1"{% else %}href="{% url 'home' %}#sec1"{% endif %}>SECTION 1</a></p>
              <p><a {% if request.get_full_path == home_url %}href="#sec2"{% else %}href="{% url 'home' %}#sec2"{% endif %}>SECTION 2</a></p>
              <p><a {% if request.get_full_path == home_url %}href="#sec3"{% else %}href="{% url 'home' %}#sec3"{% endif %}>SECTION 3</a></p>
      </div>
      <!--/.Second column-->

      <hr class="clearfix w-100 d-md-none">

      <!--Third column-->
      <div class="col-md-4 col-lg-3">
          <h5 class="title mb-4 font-bold">Address</h5>
          <!--Info-->
          <p><i class="fa fa-home mr-3"></i> San Jose, CA 95125, US</p>
          <p><i class="fa fa-envelope mr-3"></i> steve@steve-shead.com</p>
          <p><i class="fa fa-phone mr-3"></i> + 01 408 555 6789</p>
          <p><i class="fa fa-print mr-3"></i> + 01 408 555 7891</p>
      </div>
      <!--/.Third column-->

      <hr class="clearfix w-100 d-md-none">

      <!--Fourth column-->
      <div class="col-md-2 col-lg-2 text-center">
          <h5 class="title mb-4 font-bold">Follow Us</h5>
          <!--Social buttons-->
          <div class="social-section mt-2 ">
              <!--Facebook-->
              <a type="button" class="btn-floating btn-small btn-fb"><i class="fa fa-facebook"></i></a>
              <!--Twitter-->
              <a type="button" class="btn-floating btn-small btn-tw"><i class="fa fa-twitter"></i></a>
              <!--Google +-->
              <a type="button" class="btn-floating btn-small btn-gplus"><i class="fa fa-google-plus"></i></a>
              <!--Dribbble-->
              <a type="button" class="btn-floating btn-small btn-li"><i class="fa fa-linkedin"></i></a>
          </div>
      </div>
      <!--/.Fourth column-->

    </div>
  </div>
  <!--/.Footer Links-->

    <!--Copyright-->
    <div class="footer-copyright">
        <div class="container-fluid text-center">
            © {% now 'Y' %} Copyright: <a href="https://www.steve-shead.com"> Steve Shead </a>

        </div>
    </div>
    <!--/.Copyright-->

</footer>

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
      <script>$('body').scrollspy({ target: '#navbar-spy' })</script>

    {% endblock javascript %}
  </body>
</html>

base_django_template/templates/bootstrap4/field.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {% if field|is_checkbox %}
        <div class="form-group{% if using_grid_layout %} row{% endif %}">
        {% if label_class %}
            <div class="controls col-{{ bootstrap_device_type }}-offset-{{ label_size }} {{ field_class }}">
        {% endif %}
    {% endif %}
    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" {% if not field|is_checkbox %}class="form-group{% if using_grid_layout %} row{% endif %}{% else %}class="checkbox{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors%}{% if field.errors %} has-danger{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        {% if field.label and not field|is_checkbox and form_show_labels %}
            <label for="{{ field.id_for_label }}" class="form-control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% if field|is_checkboxselectmultiple %}
            {% include 'bootstrap4/layout/checkboxselectmultiple.html' %}
        {% endif %}

        {% if field|is_radioselect %}
            {% include 'bootstrap4/layout/radioselect.html' %}
        {% endif %}

        {% if not field|is_checkboxselectmultiple and not field|is_radioselect %}
            {% if field|is_checkbox and form_show_labels %}
                <label for="{{ field.id_for_label }}" class="{% if field.field.required %} requiredField{% endif %}">
                    {% crispy_field field %}
                    {{ field.label|safe }}
                    {% include 'bootstrap4/layout/help_text_and_errors.html' %}
                </label>
            {% else %}
                <div class="{{ field_class }}">
                    {% crispy_field field %}
                </div>
                {% include 'bootstrap4/layout/help_text_and_errors.html' %}
            {% endif %}
        {% endif %}
    </{% if tag %}{{ tag }}{% else %}div{% endif %}>
    {% if field|is_checkbox %}
        {% if label_class %}
            </div>
        {% endif %}
        </div>
    {% endif %}
{% endif %}

base_django_template/templates/bootstrap4/layout/field_errors_block.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="text-danger help-block">{{ error }}</p>
    {% endfor %}
{% endif %}

base_django_template/templates/pages/page.html
{% extends "base.html" %}

{% block content %}

<section id="page" class="page">

  <div class="container">

    <div class="section-heading">
      <h1 class="display-4 text-center mt-4">Page Template</h1>
      <p class="lead text-center">Section lead paragraph text.</p>
    </div>

    <div class="row pb-5">
      <div class="mr-auto col-md-10 ml-auto"><p class="lead text-center">Fames lorem ipsum dolor sit amet consectectur elit facilisi. Id egestas purus! Minim eveniet felis, nobis optio eos officiis, lorem cursus, feugiat iure libero! Saepe, distinctio incididunt rhoncus.</p></div>
    </div>

  </div>

  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row mt-5">

      <div class="col-lg-4">
        <div class="p-5 fa fa-home fa-5x mb-4"></div>
          <h2>Heading</h2>
            <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
            <p><a class="btn btn-info" href="#" role="button">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->

      <div class="col-lg-4">
        <div class="p-5 fa fa-css3 fa-5x mb-4"></div>
          <h2>Heading</h2>
            <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
            <p><a class="btn btn-info" href="#" role="button">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->

      <div class="col-lg-4">
        <div class="p-5 fa fa-code fa-5x mb-4"></div>
          <h2>Heading</h2>
            <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
            <p><a class="btn btn-info" href="#" role="button">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->

    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">

      <div class="col-md-7">
        <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>

      <div class="col-md-5">
        <img class="featurette-image img-fluid img-thumbnail mx-auto" src="http://placehold.it/500x500" alt="Generic placeholder image">
      </div>

    </div>

    <hr class="featurette-divider">

    <div class="row featurette">

      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>

      <div class="col-md-5 order-md-1">
        <img class="featurette-image img-fluid img-thumbnail mx-auto" src="http://placehold.it/500x500" alt="Generic placeholder image">
      </div>

    </div>

    <hr class="featurette-divider">

    <div class="row featurette">

      <div class="col-md-7">
        <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>

      <div class="col-md-5">
        <img class="featurette-image img-fluid img-thumbnail mx-auto" src="http://placehold.it/500x500" alt="Generic placeholder image">
      </div>

    </div>

    <hr class="featurette-divider">

    <div class="row pb-5">
      <div class="mr-auto col-md-10 ml-auto"><p class="lead text-center">Molestie nihil fermentum, donec quod nobis neque maecenas quos, pretium hendrerit aenean! Cillum ullamco facilis conubia voluptate dictumst duis ea, auctor, dolor, ex, odio mauris sit cupidatat adipisci repellat! Mauris sapiente consectetuer cupiditate atque wisi laboris bibendum, platea? Leo tellus porro? Pariatur magna, necessitatibus nisi vehicula repudiandae semper cumque.</p></div>
    </div>

</section>

{% endblock content %}

base_django_template/templates/pages/thank_you.html
{% extends "contact_base.html" %}

{% block content %}

<section class="thank_you pt-5">
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
        <h1>Thank You!</h1>
          <p class="lead">We have received your<strong> message.</strong></p>
          <i class="fa fa-envelope-o fa-5x"></i>
          <br />
          <p class="pt-4 pb-3">We'll get back to you shortly.</p>
        <p class="lead">
          <a class="btn btn-info" href="/" role="button">Homepage</a>
          <a class="btn btn-success" href="{% url 'account_signup' %}" role="button">Register</a>
        </p>
    </div>
  </div>
</div>
</section>

{% endblock content %}

base_django_template/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row mb-5">

  <div class="col-sm-12">
    <a class="btn btn-info" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-info" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

base_django_template/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
<div class="container">
  <div class="row mb-5">
    <div class="col-sm-12">

  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-info">Update</button>
      </div>
    </div>
  </form>

    </div>
  </div>
</div>
{% endblock %}

base_django_template/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <div class="row">

    <h2>Users</h2>

    <div class="list-group">
      {% for user in user_list %}
        <a href="{% url 'users:detail' user.username %}" class="list-group-item">
          <h4 class="list-group-item-heading">{{ user.username }}</h4>
        </a>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock content %}